language: go
go:
  - 1.5.1
  - 1.4
sudo: false
before_install:
  - mkdir /tmp/fdm
  - wget https://raw.githubusercontent.com/pki-io/fdm/master/fdm -O /tmp/fdm/fdm
  - chmod +x /tmp/fdm/fdm
  - export PATH=$PATH:/tmp/fdm
  - go get github.com/stretchr/testify
  - go get github.com/modocache/gover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - make get-deps
  - fdm test -coverprofile=config.coverprofile ./config
  - fdm test -coverprofile=crypto.coverprofile ./crypto
  - fdm test -coverprofile=document.coverprofile ./document
  - fdm test -coverprofile=entity.coverprofile ./entity
  - fdm test -coverprofile=fs.coverprofile ./fs
  - fdm test -coverprofile=index.coverprofile ./index
  - fdm test -coverprofile=node.coverprofile ./node
  - fdm test -coverprofile=x509.coverprofile ./x509
  - gover
  - goveralls -coverprofile=gover.coverprofile -service travis-ci
